### ISSUE TITLE
Closing stories broken

### ISSUE THREAD

**Issue by herdidi47** [iHelp101/XInsta#45] opened 2018-05-26 20:06 UTC
if you close IG stories (manually or automatic if you run out of new stories, the stories is freezing.

log and video here : https://drive.google.com/folderview?id=1ZjTJelqakkuGA4dqdqJOsbvdluEUfOY2

additional info : latest hook with experimental on. xinsta 2.0.5

**Comment by jizzy002** [comment] 2018-05-26 20:10
Same issue here

**Comment by iHelp101** [comment] 2018-05-26 20:37
I am not able to replicate this issue on this specific Instagram version. Does this issue only occur video stories? Or do images have this issue as well?

**Comment by jizzy002** [comment] 2018-05-26 20:39
Images and videos.

**Comment by iHelp101** [comment] 2018-05-26 20:45
Since Instagram is migrating to a new stories viewer/player (HeroPlayer) lets make sure XInsta is the cause the the freezing/crash. Open Xposed -> Three Line Icon -> Modules -> Uncheck XInsta and reboot. Verify if the issue is no longer present.

**Comment by jizzy002** [comment] 2018-05-26 21:04
Disabled Xinsta,rebooted and tested stories,works again normally

**Comment by iHelp101** [comment] 2018-05-26 21:07
Alright, XInsta has four hooks related to stories timers (MediaPlayer, ExoPlayer, HeroPlayer, and Image Timer). Give me a few minutes and I will make a test APK. The image timer hooks hooks a method related to back press, so it is the likely culprit.

**Comment by jizzy002** [comment] 2018-05-26 21:11
Thanks for your fast responses!

**Comment by iHelp101** [comment] 2018-05-26 21:13
Here is the test APK with the stories image timer disabled. It is an older hook that hasn't changed in a while, so it is interesting that it is having issues. 

https://drive.google.com/open?id=1OXZUrkLC0NVUMR8t0TMEAqMd9AqpOJYw

**Comment by iHelp101** [comment] 2018-05-26 21:27
Just to make sure I understand lets rephrase this. I have my understanding of the issue below.

Disable Stories Timer Feature On - Issue
Disable Stories Timer Feature Off - No Issue

**Comment by jizzy002** [comment] 2018-05-26 21:30
Yeah just like that.

**Comment by iHelp101** [comment] 2018-05-26 21:43
Okay, I am looking further into it. This is one of the last versions of Instagram before HeroPlayer was integrated fully. So it may be a hiccup with the hook. I am looking deeper into the code. The only hook that is related to back presses is the stories image timer hook. This hook when a video hook does not work will stop a post from initially exiting automatically (Count down). The video hook is in charge of looping the video, which if not working makes the post basically freeze at the end. Is this the issue? Or is this issue that you can not back press out of stories?

**Comment by jizzy002** [comment] 2018-05-26 21:49
Before the 2.0.5 update,you could normally exit (backpress), but stories would freeze not loop.
The main issue now is that you cannot backpress out of stories without fully freezing a fullscreen frame of the video or picture.

**Comment by iHelp101** [comment] 2018-05-26 22:31
I have a local Git to track changes between updates, so I have been looking for changes that may cause this unexpected behavior. I reversed a hook related to hiding stories views (On main feed). Maybe it has a conflict with stories when closing. 

https://drive.google.com/open?id=1w4QtRLkPVxkJoFpf19GbqkpYpWGK1iT9

**Comment by jizzy002** [comment] 2018-05-26 22:44
Now video doesn't want to loop but it stops, not a huge problem for me but exiting out of the stories works normally. Everything else works fine i think.

**Comment by iHelp101** [comment] 2018-05-26 22:54
Alright, use Instagram like you normally would for the weekend and report any issues you have. The loop hook is not going to work with this version due to HeroPlayer being half implemented (Missing setLoop method).

**Comment by jizzy002** [comment] 2018-05-26 22:58
I will watch out for any other issues, thanks for fixing this so fast 👍

**Comment by herdidi47** [comment] 2018-05-27 02:31
so i just try you test build, and the problem still persist for me :/ already trying to turn the "Disable Stories Timer" off and still persist

**Comment by iHelp101** [comment] 2018-05-27 03:01
Alright, lets make sure it is an XInsta issue. Open Xposed -> Three Line Icon -> Modules -> Uncheck XInsta and reboot. Verify if the issue is no longer present.

**Comment by herdidi47** [comment] 2018-05-27 03:03
i already tried it since you official 2.0.5 and yes, it's xinsta issue. if i turn it off in xposed, stories working perfectly

**Comment by iHelp101** [comment] 2018-05-27 03:13
Okay, can you get a logcat of this issue? That should help pinpoint what is causing this. On newer versions of Android you can get a bug report instead (In developer settings click Take Bug Report after replicating the issue).

**Comment by herdidi47** [comment] 2018-05-27 14:53
issue still persist :(( should i try downgrade instagram?

**Comment by iHelp101** [comment] 2018-05-27 14:56
You can give it a try. If we can nail it down to a specific Instagram version that helps. But since you didn't have this issue with 2.0.4 it might be a conflict between hooks.

**Comment by herdidi47** [comment] 2018-05-27 15:43
after trying a few stuff, i found out if i turn off storage permission, the issue is gone, while turning it back on it appear again

**Comment by iHelp101** [comment] 2018-05-27 15:47
Okay, so it is one of the settings. Can you disable some stories related settings back and forth to figure out which is the issue? So Stories Privacy, Hide Stories, and Stories Timer are the main ones.

**Comment by herdidi47** [comment] 2018-05-27 16:19
i mean the instagram storage permission. and i already tried what you said. looks like if 3 of them is turned off, stories can close correctly

**Comment by herdidi47** [comment] 2018-05-27 16:26
weird.. i just turn back to official xposed 2.0.5 release, and suddenly the problem only persist if the stories timer is on. (tried while turning on and off stories privacy) i never turn on hide stories

**Comment by iHelp101** [comment] 2018-05-27 16:35
Alright, I reversed some changes. Let try this. The two I am thinking are the likely issue are Stories Timer and Stories Privacy. In 2.0.5 these had a conflict with one setting, which is resolved in these test APKs. The conflict resolution may make it more clear to which is the exact issue.

https://drive.google.com/open?id=1w4QtRLkPVxkJoFpf19GbqkpYpWGK1iT9

**Comment by herdidi47** [comment] 2018-05-27 16:42
now the problem occur if stories provacy is on. stories timer working perfectly while on (but no loop)

**Comment by iHelp101** [comment] 2018-05-27 17:02
Alright,  we have our answer. The Instagram version you are on is half integrated with HeroPlayer, so looping is not supported. Let me look deeper into Stories Privacy and what might be triggering this issue.

**Comment by herdidi47** [comment] 2018-05-27 17:05
updating back to latest stable instagram in playstore. all looks promising. goodluck and thanks a lot for your help and respond. best developer so far :D 👍👍 let me know if you need me testing stuff

**Comment by iHelp101** [comment] 2018-05-28 14:48
This issue turned out to be a hook issue with stories privacy. One of the hooks (Prevent logging of viewing) was conflicting and for some devices and story types was causing this issue. I have updated the hooks for some of the recent versions and will be backlogging for the remaining affected versions (Looks like last 15 or so Instagram versions).

**Comment by herdidi47** [comment] 2018-05-28 15:29
so you only need fix the hook?

**Closed** 2018-06-12 04:15 UTC
