### ISSUE TITLE
Native crash

### ISSUE THREAD

**Issue by jacky8399** [iHelp101/XInsta#96] opened 2019-04-29 11:51 UTC
Instagram always crashes with native crash. When I update to the latest hooks from pastebin, Instagram will stop crashing for a while until after some time it starts to crash again. I have the latest version of Instagram (151414277).
Stack trace of the native crash:
![Screenshot_20190429-193333__01](https://user-images.githubusercontent.com/7542810/56894045-3a3ac400-6ab7-11e9-85ad-1a52a2da1ec7.jpg)
Xposed stack trace when launching Instagram:
```
04-29 19:46:41.524 I/Xposed  (19084): XInsta - XInsta Initialized
04-29 19:46:41.528 I/Xposed  (19084): XInsta - Instagram Version Code: 151414277
04-29 19:46:41.529 I/Xposed  (19084): XInsta - Device Codename: ONEPLUS A5000
04-29 19:46:41.530 I/Xposed  (19084): XInsta - Android Version: 8.1.0
04-29 19:46:41.532 I/Xposed  (19084): XInsta - XInsta Version 2.1.0
04-29 19:46:42.071 I/Xposed  (19084): XInsta - Hooks Fetched!
04-29 19:46:42.324 I/Xposed  (19084): XInsta - Date Failed5 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-29 19:46:42.326 I/Xposed  (19084): XInsta - Date Failed5 Class - X.0g2
```

**Comment by mrsdbskn** [comment] 2019-04-29 12:55
I can confirm the crash as I have the same issue.

**Comment by iHelp101** [comment] 2019-04-30 22:06
Are you still having this issue?

**Comment by jacky8399** [comment] 2019-05-01 06:06
I stopped having the issue when I was using 151414277, but none of the features (excluding image downloading and profile pic zoom) were working. 

However, once I updated to 152367502, I encountered the same problem, albeit with a different class this time (`X.1DB.D`). `X.1DB.D`, like the other class, appears to take an argument of type java.io.Reader.

**Comment by iamdexter** [comment] 2019-05-03 01:31
The same problem with the testing hooks, I returned to 1514142...

**Comment by iHelp101** [comment] 2019-05-03 16:53
If someone can get me a logcat or bug report of the crash it would really help. I can't reproduce the crash sadly, so testing a fix is very tricky.

**Comment by jacky8399** [comment] 2019-05-04 07:37
here is the logcat for the crash
https://pastebin.com/q5wSEjjp

**Comment by iHelp101** [comment] 2019-07-10 23:30
Fixed in next update.

**Closed by iHelp101** 2019-07-10 23:30 UTC
